### ISSUE TITLE
Disabling N. beacons crashes the client, but not so much the server

### ISSUE THREAD

**Issue by JuergenSchT** [OroArmor/Netherite-Plus-Mod#33]
Minecraft: 1.16.3
FabricAPI: 0.23.0+build.410
Netherite Plus Mod: 1.0.0
Changing _"enabled": {"beacon":_ from true to false crashes the Minecraft client. [LINK](https://paste.ee/p/oWjUM).
Enacting the same change in the config of a server does not crash it, but prints a warning. [LINK](https://paste.ee/p/1re02).
Connecting to said server works. When looking "beacon" on the Creative menu, an errored "Netherite Beacon" shows up, whose namespaced ID is "minecraft:air".

**Comment by OroArmor** [comment]
Alright! This is fixed. Im not fixing the issue you brought up with the server warning, mostly because I don't want the whole datapack for the mod to be in code, (I should add the other files back in for that), mostly so that people can make their own datapacks and for mod packs. Thanks for letting me know!
