### ISSUE TITLE
Add compatibility for [BetterEnd]

### ISSUE THREAD

**Issue by milkev** [OroArmor/Netherite-Plus-Mod#57]
**What is the mod and for which platform is it for**
BetterEnd, Fabric

**What feature(s) is in conflict**
Anvil recipes that betterend creates do not work in the netherite anvil. However these recipes work with other modded anvils (i tested DragonLoot's anvil)

I wasnt sure if i should have submitted it as a bug or compatability.

**Comment by OroArmor** [comment]
It looks like they added a custom anvil recipe type. Ill ask the devs about it

**Comment by OroArmor** [comment]
Alright after some more investigation, I have decided to leave it as it. The way that the recipe is checked is quite intrusive, and should be done from their end if they wish to add support. As well, the uniqueness of the recipes makes me more inclined to leave it on the vanilla anvil, rather than add it to the netherite anvil. Thank you for suggesting! ill add a issue on their end.

**Comment by OroArmor** [comment]
Alright i added this into my next release! thank you!
